# -*- coding: utf-8 -*-
# Copyright 2016 SYLEAM
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'jean-bouteille Profile',
    'version': '14.0',
    'category': 'Custom',
    'description': """Profile for jean-bouteille""",
    'author': 'Subteno',
    'website': 'https://www.subteno-it.fr/',
    'depends': [
        'base',
        'mrp',
        'purchase',
        'delivery',
        'sale',
        'sale_subscription',
        'website_sale',
    ],
    'data': [
        'views/sale_subscription_stage.xml',
        'views/product_product.xml',
        'views/product_views.xml',
        'templates/assets.xml',
        'templates/shop_category.xml',
        'views/stock_move_view.xml',
        'views/stock_quant_view.xml',
        'views/stock_move_line_views.xml',
        'views/templates.xml',
        'report/sale_report_jb.xml',
        'report/report_purchase_order.xml',
        'report/report_stock.xml',
        'report/purchase_report_views.xml',
        'views/sale_order_view.xml',
        'views/purchase_order_view.xml',
        'data/res_group.xml',
        'security/ir.model.access.csv',
        'views/export_edi_file.xml',
        'views/product_packaging.xml',
        'views/product_template.xml',
        'views/stock_picking.xml',
        'data/edi_export.xml',
        'views/stock_production_lot.xml',
        'data/cron_import_snapshots.xml',
        'data/cron_import_reception_delivery.xml',
        'views/res_company_view.xml',
        'views/mrp_production.xml',
        'views/stock_orderpoint_view.xml',
    ],
    'qweb': [
    ],
    'installable': True,
    'application': True,
    'license': 'AGPL-3',
}
